version: "3.9"
services: 
  app: 
    build: .
    #command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    links:
     - db
  db:
    image: mongo
    #ports:
    # - 27017:27017
    restart: always
    volumes:
      - mongodata:/data/db
  mongo-client:
    image: mongoclient/mongoclient
    restart: always
    ports:
      - "5007:3000"
    environment:
      - MONGO_URL=mongodb://db:27017

volumes:
  mongodata: 

